[2025-01-07T13:02:11.743+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-07T13:02:11.822+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.random_dice scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-07T13:02:11.843+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.random_dice scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-07T13:02:11.844+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-01-07T13:02:11.889+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): random_dice> on 2025-01-01 00:00:00+00:00
[2025-01-07T13:02:11.900+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1333) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-07T13:02:11.904+0000] {standard_task_runner.py:63} INFO - Started process 1342 to run task
[2025-01-07T13:02:11.903+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'random_dice', 'scheduled__2025-01-01T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/skelet.py', '--cfg-path', '/tmp/tmp27s2r6u3']
[2025-01-07T13:02:11.908+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask random_dice
[2025-01-07T13:02:12.009+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag.random_dice scheduled__2025-01-01T00:00:00+00:00 [running]> on host 006c1e931b5c
[2025-01-07T13:02:12.215+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='random_dice' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:00:00+00:00'
[2025-01-07T13:02:12.220+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-07T13:02:12.262+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-07T13:02:12.264+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/skelet.py", line 17, in random_dice
    raise ValueError(f'Odd {val}')
ValueError: Odd 5
[2025-01-07T13:02:12.285+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=random_dice, run_id=scheduled__2025-01-01T00:00:00+00:00, execution_date=20250101T000000, start_date=20250107T130211, end_date=20250107T130212
[2025-01-07T13:02:12.312+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 34 for task random_dice (Odd 5; 1342)
[2025-01-07T13:02:12.366+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-01-07T13:02:12.390+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-07T13:02:12.394+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
