[2025-01-07T13:02:35.966+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-07T13:02:35.993+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.random_dice manual__2025-01-07T13:02:11.825667+00:00 [queued]>
[2025-01-07T13:02:36.004+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.random_dice manual__2025-01-07T13:02:11.825667+00:00 [queued]>
[2025-01-07T13:02:36.005+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2025-01-07T13:02:36.029+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): random_dice> on 2025-01-07 13:02:11.825667+00:00
[2025-01-07T13:02:36.037+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1382) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-07T13:02:36.039+0000] {standard_task_runner.py:63} INFO - Started process 1383 to run task
[2025-01-07T13:02:36.039+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'random_dice', 'manual__2025-01-07T13:02:11.825667+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/skelet.py', '--cfg-path', '/tmp/tmp3g1c4_0t']
[2025-01-07T13:02:36.040+0000] {standard_task_runner.py:91} INFO - Job 53: Subtask random_dice
[2025-01-07T13:02:36.109+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag.random_dice manual__2025-01-07T13:02:11.825667+00:00 [running]> on host 006c1e931b5c
[2025-01-07T13:02:36.279+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='random_dice' AIRFLOW_CTX_EXECUTION_DATE='2025-01-07T13:02:11.825667+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-07T13:02:11.825667+00:00'
[2025-01-07T13:02:36.281+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-07T13:02:36.303+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-07T13:02:36.304+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/skelet.py", line 17, in random_dice
    raise ValueError(f'Odd {val}')
ValueError: Odd 5
[2025-01-07T13:02:36.322+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=first_dag, task_id=random_dice, run_id=manual__2025-01-07T13:02:11.825667+00:00, execution_date=20250107T130211, start_date=20250107T130235, end_date=20250107T130236
[2025-01-07T13:02:36.342+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 53 for task random_dice (Odd 5; 1383)
[2025-01-07T13:02:36.375+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-01-07T13:02:36.398+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-07T13:02:36.402+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
