[2025-01-07T13:02:34.690+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-07T13:02:34.736+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.random_dice scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-01-07T13:02:34.750+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.random_dice scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-01-07T13:02:34.751+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2025-01-07T13:02:34.774+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): random_dice> on 2025-01-04 00:00:00+00:00
[2025-01-07T13:02:34.782+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1378) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-07T13:02:34.784+0000] {standard_task_runner.py:63} INFO - Started process 1380 to run task
[2025-01-07T13:02:34.784+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'random_dice', 'scheduled__2025-01-04T00:00:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/skelet.py', '--cfg-path', '/tmp/tmp7589af26']
[2025-01-07T13:02:34.785+0000] {standard_task_runner.py:91} INFO - Job 51: Subtask random_dice
[2025-01-07T13:02:34.844+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag.random_dice scheduled__2025-01-04T00:00:00+00:00 [running]> on host 006c1e931b5c
[2025-01-07T13:02:34.961+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='random_dice' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-04T00:00:00+00:00'
[2025-01-07T13:02:34.962+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-07T13:02:34.984+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-07T13:02:34.985+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/skelet.py", line 17, in random_dice
    raise ValueError(f'Odd {val}')
ValueError: Odd 5
[2025-01-07T13:02:35.000+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=first_dag, task_id=random_dice, run_id=scheduled__2025-01-04T00:00:00+00:00, execution_date=20250104T000000, start_date=20250107T130234, end_date=20250107T130234
[2025-01-07T13:02:35.017+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 51 for task random_dice (Odd 5; 1380)
[2025-01-07T13:02:35.039+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-01-07T13:02:35.059+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-07T13:02:35.062+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
