[2025-01-07T13:02:12.053+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-07T13:02:12.128+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.random_dice scheduled__2025-01-02T00:00:00+00:00 [queued]>
[2025-01-07T13:02:12.160+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.random_dice scheduled__2025-01-02T00:00:00+00:00 [queued]>
[2025-01-07T13:02:12.161+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-01-07T13:02:12.200+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): random_dice> on 2025-01-02 00:00:00+00:00
[2025-01-07T13:02:12.211+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1334) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-07T13:02:12.214+0000] {standard_task_runner.py:63} INFO - Started process 1343 to run task
[2025-01-07T13:02:12.214+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'random_dice', 'scheduled__2025-01-02T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/skelet.py', '--cfg-path', '/tmp/tmpjpuetumh']
[2025-01-07T13:02:12.216+0000] {standard_task_runner.py:91} INFO - Job 35: Subtask random_dice
[2025-01-07T13:02:12.294+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag.random_dice scheduled__2025-01-02T00:00:00+00:00 [running]> on host 006c1e931b5c
[2025-01-07T13:02:12.451+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='random_dice' AIRFLOW_CTX_EXECUTION_DATE='2025-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-02T00:00:00+00:00'
[2025-01-07T13:02:12.452+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-07T13:02:12.484+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-07T13:02:12.486+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/skelet.py", line 17, in random_dice
    raise ValueError(f'Odd {val}')
ValueError: Odd 3
[2025-01-07T13:02:12.506+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=random_dice, run_id=scheduled__2025-01-02T00:00:00+00:00, execution_date=20250102T000000, start_date=20250107T130212, end_date=20250107T130212
[2025-01-07T13:02:12.525+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 35 for task random_dice (Odd 3; 1343)
[2025-01-07T13:02:12.552+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-01-07T13:02:12.577+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-07T13:02:12.582+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
