[2025-01-07T13:14:09.021+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-07T13:14:09.067+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag_execution_date.even_only scheduled__2024-12-27T00:00:00+00:00 [queued]>
[2025-01-07T13:14:09.087+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag_execution_date.even_only scheduled__2024-12-27T00:00:00+00:00 [queued]>
[2025-01-07T13:14:09.089+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-01-07T13:14:09.151+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): even_only> on 2024-12-27 00:00:00+00:00
[2025-01-07T13:14:09.161+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1537) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-07T13:14:09.163+0000] {standard_task_runner.py:63} INFO - Started process 1543 to run task
[2025-01-07T13:14:09.163+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_dag_execution_date', 'even_only', 'scheduled__2024-12-27T00:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/first_dag_execution_date.py', '--cfg-path', '/tmp/tmp4tkn52lk']
[2025-01-07T13:14:09.165+0000] {standard_task_runner.py:91} INFO - Job 58: Subtask even_only
[2025-01-07T13:14:09.249+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag_execution_date.even_only scheduled__2024-12-27T00:00:00+00:00 [running]> on host 006c1e931b5c
[2025-01-07T13:14:09.410+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag_execution_date' AIRFLOW_CTX_TASK_ID='even_only' AIRFLOW_CTX_EXECUTION_DATE='2024-12-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-27T00:00:00+00:00'
[2025-01-07T13:14:09.413+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-07T13:14:09.440+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-01-07T13:14:09.442+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-07T13:14:09.444+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/first_dag_execution_date.py", line 18, in even_only
    raise ValueError(f'Odd day: {execution_date}')
ValueError: Odd day: 2024-12-27 00:00:00+00:00
[2025-01-07T13:14:09.464+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=first_dag_execution_date, task_id=even_only, run_id=scheduled__2024-12-27T00:00:00+00:00, execution_date=20241227T000000, start_date=20250107T131409, end_date=20250107T131409
[2025-01-07T13:14:09.491+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 58 for task even_only (Odd day: 2024-12-27 00:00:00+00:00; 1543)
[2025-01-07T13:14:09.540+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-01-07T13:14:09.561+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
